#!/usr/bin/env python3
# ============================================================
# VOLTRIX blind test JJA 2026 — librairie ReportLab (styles + helpers)
# Conforme brief report.md : fonts FreeSerif/NotoSerifSC enregistrées,
# install_font_fallback(), palette cascade (seed 21), tables Paragraph(),
# hAlign CENTER, repeatRows=1, TOC auto (TocDocTemplate + multiBuild).
# ============================================================
import os
import sys
import hashlib

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    KeepTogether, CondPageBreak, HRFlowable, Image,
)
from reportlab.platypus.tableofcontents import TableOfContents
from PIL import Image as PILImage

PDF_SKILL_SCRIPTS = '/home/z/my-project/skills/pdf/scripts'
if PDF_SKILL_SCRIPTS not in sys.path:
    sys.path.insert(0, PDF_SKILL_SCRIPTS)

FONT_DIR = '/usr/share/fonts'

# ── Enregistrement des fonts (seules autorisées) ──
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
# 'Noto Sans SC' : fichiers statiques absents de cet environnement (fonte variable
# uniquement) — la chaîne de fallback pdf.py exige le NOM enregistré ; on tente la
# fonte variable puis on aliasse sur SerifSC (repli rare : document français).
try:
    pdfmetrics.registerFont(TTFont('Noto Sans SC', f'{FONT_DIR}/truetype/chinese/NotoSansSC[wght].ttf'))
    pdfmetrics.registerFont(TTFont('Noto Sans SC Bold', f'{FONT_DIR}/truetype/chinese/NotoSansSC[wght].ttf'))
except Exception:
    pdfmetrics.registerFont(TTFont('Noto Sans SC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
    pdfmetrics.registerFont(TTFont('Noto Sans SC Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('Noto Sans SC', normal='Noto Sans SC', bold='Noto Sans SC Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold', italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback  # noqa: E402
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade, seed 21) ━━
PAGE_BG       = colors.HexColor('#f2f1f0')
SECTION_BG    = colors.HexColor('#f1f0ef')
CARD_BG       = colors.HexColor('#ecebe8')
TABLE_STRIPE  = colors.HexColor('#ebebe9')
HEADER_FILL   = colors.HexColor('#675e45')
COVER_BLOCK   = colors.HexColor('#78715d')
BORDER        = colors.HexColor('#c2beb0')
ICON          = colors.HexColor('#a08f5e')
ACCENT        = colors.HexColor('#96771c')
ACCENT_2      = colors.HexColor('#5537b0')
TEXT_PRIMARY  = colors.HexColor('#22211f')
TEXT_MUTED    = colors.HexColor('#87857d')
SEM_SUCCESS   = colors.HexColor('#47845b')
SEM_WARNING   = colors.HexColor('#a68b56')
SEM_ERROR     = colors.HexColor('#8f4a44')
SEM_INFO      = colors.HexColor('#416990')
TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = TABLE_STRIPE

# ── Géométrie ──
MARGIN = 0.9 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25

# ── Styles (français → FreeSerif) ──
S = {}
S['body'] = ParagraphStyle('body', fontName='FreeSerif', fontSize=10.5, leading=17,
                           alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY, spaceAfter=8)
S['bodyLeft'] = ParagraphStyle('bodyLeft', parent=S['body'], alignment=TA_LEFT)
S['h1'] = ParagraphStyle('h1', fontName='FreeSerif', fontSize=20, leading=26,
                         textColor=TEXT_PRIMARY, spaceBefore=6, spaceAfter=4)
S['h2'] = ParagraphStyle('h2', fontName='FreeSerif', fontSize=14, leading=19,
                         textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
S['h3'] = ParagraphStyle('h3', fontName='FreeSerif', fontSize=11.5, leading=16,
                         textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=5)
S['bullet'] = ParagraphStyle('bullet', parent=S['bodyLeft'], leftIndent=14, bulletIndent=2, spaceAfter=5)
S['caption'] = ParagraphStyle('caption', fontName='FreeSerif-Italic', fontSize=8.5, leading=12,
                              alignment=TA_CENTER, textColor=TEXT_MUTED, spaceBefore=3, spaceAfter=6)
S['quote'] = ParagraphStyle('quote', fontName='FreeSerif-Italic', fontSize=10.5, leading=17,
                            leftIndent=24, textColor=TEXT_PRIMARY, borderPadding=6, spaceAfter=10)
S['tocTitle'] = ParagraphStyle('tocTitle', fontName='FreeSerif', fontSize=18, leading=24,
                               textColor=TEXT_PRIMARY, spaceAfter=14)
S['th'] = ParagraphStyle('th', fontName='FreeSerif', fontSize=8.6, leading=11,
                         textColor=colors.white, alignment=TA_CENTER)
S['td'] = ParagraphStyle('td', fontName='FreeSerif', fontSize=8.6, leading=11,
                         textColor=TEXT_PRIMARY, alignment=TA_CENTER)
S['tdl'] = ParagraphStyle('tdl', parent=S['td'], alignment=TA_LEFT)
S['tdr'] = ParagraphStyle('tdr', parent=S['td'], alignment=TA_RIGHT)
# cellules compactes du tableau match-par-match
S['mx'] = ParagraphStyle('mx', fontName='FreeSerif', fontSize=7.4, leading=9.2,
                         textColor=TEXT_PRIMARY, alignment=TA_CENTER)
S['mxl'] = ParagraphStyle('mxl', parent=S['mx'], alignment=TA_LEFT)
S['mth'] = ParagraphStyle('mth', fontName='FreeSerif', fontSize=7.8, leading=9.6,
                          textColor=colors.white, alignment=TA_CENTER)
S['statBig'] = ParagraphStyle('statBig', fontName='FreeSerif', fontSize=20, leading=24,
                              textColor=ACCENT, alignment=TA_CENTER)
S['statLabel'] = ParagraphStyle('statLabel', fontName='FreeSerif', fontSize=8.5, leading=11.5,
                                textColor=TEXT_MUTED, alignment=TA_CENTER)


def P(text, style='body'):
    return Paragraph(text, S[style])


def add_heading(text, style, level=0):
    """Titre avec signet TOC cliquable (TocDocTemplate)."""
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def chapter(story, num, title, first_body=None):
    """Chapitre H1 : saut conditionnel anti-orphelin + titre + règle accent + 1er paragraphe."""
    els = [
        add_heading(f'{num}.  {title}', S['h1'], level=0),
        HRFlowable(width='100%', thickness=1.4, color=ACCENT, spaceBefore=2, spaceAfter=10),
    ]
    if first_body is not None:
        els.append(first_body)
    story.append(CondPageBreak(H1_ORPHAN))
    story.append(KeepTogether(els))


def h2(story, text, first_body=None):
    els = [add_heading(text, S['h2'], level=1)]
    if first_body is not None:
        els.append(first_body)
    story.append(KeepTogether(els))


def make_table(header, rows, ratios, style_header='th', style_cell='td',
               repeat=1, font_align=None, width_frac=0.98):
    """Table centrée : toutes cellules Paragraph, largeur ≤ disponible, zébrage palette."""
    total = sum(ratios)
    widths = [r / total * AVAIL_W * width_frac for r in ratios]
    data = [[Paragraph(f'<b>{h}</b>', S[style_header]) for h in header]]
    for row in rows:
        cells = []
        for i, c in enumerate(row):
            st = style_cell
            if font_align and font_align[i] in ('l', 'r', 'c'):
                st = {'l': 'tdl', 'r': 'tdr', 'c': 'td'}[font_align[i]]
            cells.append(c if isinstance(c, (Paragraph, Image)) else Paragraph(str(c), S[st]))
        data.append(cells)
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=repeat)
    styles = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 3.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3.5),
    ]
    for i in range(1, len(data)):
        styles.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD))
    t.setStyle(TableStyle(styles))
    return t


def table_block(story, title_text, header, rows, ratios, caption=None, font_align=None, keep=True):
    story.append(Spacer(1, 10))
    t = make_table(header, rows, ratios, font_align=font_align)
    cap = Paragraph(caption, S['caption']) if caption else None
    if keep and len(rows) <= 15:
        els = [t] if not title_text else [Paragraph(title_text, S['h3']), t]
        if cap:
            els.append(cap)
        story.append(KeepTogether(els))
    else:
        if title_text:
            story.append(Paragraph(title_text, S['h3']))
        story.append(t)
        if cap:
            story.append(cap)
    story.append(Spacer(1, 8))


def embed_image(path, max_width=None, max_height=None):
    if max_width is None:
        max_width = AVAIL_W
    if max_height is None:
        max_height = A4[1] * 0.35
    pil = PILImage.open(path)
    ow, oh = pil.size
    ratio = min(max_width / ow if ow > max_width else 1.0, max_height / oh if oh > max_height else 1.0)
    return Image(path, width=ow * ratio, height=oh * ratio)


def figure_block(story, png_path, caption, max_height=None):
    story.append(Spacer(1, 14))
    img = embed_image(png_path, max_width=AVAIL_W, max_height=max_height or A4[1] * 0.33)
    cap = Paragraph(caption, S['caption'])
    story.append(KeepTogether([img, Spacer(1, 6), cap]))
    story.append(Spacer(1, 12))


def callout_row(story, stats):
    """Rangée de 3-4 CalloutBox de statistiques (data-to-ink)."""
    cells = []
    for big, label in stats:
        inner = Table(
            [[Paragraph(f'<b>{big}</b>', S['statBig'])], [Paragraph(label, S['statLabel'])]],
            colWidths=[AVAIL_W * 0.9 / len(stats) - 10],
        )
        inner.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
            ('BOX', (0, 0), (-1, -1), 0.8, ACCENT),
            ('TOPPADDING', (0, 0), (-1, 0), 8),
            ('BOTTOMPADDING', (0, -1), (-1, -1), 8),
            ('TOPPADDING', (0, 1), (-1, 1), 1),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 1),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        cells.append(inner)
    outer = Table([cells], colWidths=[AVAIL_W * 0.9 / len(stats)] * len(stats), hAlign='CENTER')
    outer.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(Spacer(1, 6))
    story.append(KeepTogether(outer))
    story.append(Spacer(1, 10))


def callout_note(story, text, color=ACCENT):
    """Encadré verdict : bordure gauche accent + fond teinté."""
    inner = Table([[Paragraph(text, S['bodyLeft'])]], colWidths=[AVAIL_W * 0.96 - 8])
    inner.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, color),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
    ]))
    story.append(Spacer(1, 4))
    story.append(KeepTogether(inner))
    story.append(Spacer(1, 8))


def fr(x, nd=4):
    """Format français virgule décimale."""
    if x is None:
        return '—'
    return f'{x:.{nd}f}'.replace('.', ',')


def pct(x, nd=1):
    if x is None:
        return '—'
    return (f'{x * 100:.{nd}f}').replace('.', ',') + ' %'


# ── Modèle de document avec TOC + pieds de page romain/arabe ──
class TocDocTemplate(SimpleDocTemplate):
    def beforeDocument(self):
        # Les footers sont dessinés au DÉBUT de chaque page (onPage) : le corps
        # commence donc toujours avec la valeur de la passe précédente (stable
        # dès la passe 2 ; multiBuild fait au moins 2 passes avec un TOC).
        self._body_start_prev = getattr(self, '_body_start_page', None)
        self._body_start_page = None

    def afterFlowable(self, flowable):
        # Début du corps = premier signet de niveau 0 (chapitre 1) — robuste aux
        # passes multiBuild (un attribut posé sur un flowable marqueur ne survit
        # pas de façon fiable d'une passe à l'autre).
        if (self._body_start_page is None and hasattr(flowable, 'bookmark_name')
                and getattr(flowable, 'bookmark_level', 0) == 0):
            self._body_start_page = self.page
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            # Numéro AFFICHÉ (arabe remis à 1 au début du corps — le TOC exige un entier)
            if self._body_start_page is not None and self.page >= self._body_start_page:
                display = self.page - self._body_start_page + 1
            else:
                display = self.page
            self.notify('TOCEntry', (level, text, display, key))
            self.canv.bookmarkPage(key)
            self.canv.addOutlineEntry(text, key, level=level, closed=False)

    def footer_text(self, page):
        roman = {1: 'i', 2: 'ii', 3: 'iii', 4: 'iv', 5: 'v', 6: 'vi', 7: 'vii', 8: 'viii'}
        body_start = self._body_start_prev if self._body_start_prev is not None else self._body_start_page
        if body_start is None or page < body_start:
            return roman.get(page, str(page))
        return str(page - body_start + 1)


DOC_TITLE = "VOLTRIX bet — Simulation aveugle de validation · Juin–Juillet–Août 2026"


def on_page(canvas, doc):
    canvas.saveState()
    # En-tête : titre + règle accent
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    # Pied : auteur gauche + numéro droite + règle légère
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, 'Rapport d’audit · données ESPN · moteur v2.1 inchangé')
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, doc.footer_text(doc.page))
    canvas.restoreState()
