# -*- coding: utf-8 -*-
"""Génère le corps du dossier technique VOLTRIX bet (ReportLab, TOC auto)."""
import os, sys, hashlib

PDF_SKILL = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(PDF_SKILL, 'scripts'))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, Image, KeepTogether, CondPageBreak,
                                HRFlowable)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from PIL import Image as PILImage

# ── Polices ──────────────────────────────────────────────────────────────
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#eff0f1')
SECTION_BG    = colors.HexColor('#edeeee')
CARD_BG       = colors.HexColor('#e7e9ea')
TABLE_STRIPE  = colors.HexColor('#eeeff0')
HEADER_FILL   = colors.HexColor('#3d5059')
COVER_BLOCK   = colors.HexColor('#506671')
BORDER        = colors.HexColor('#aab6bc')
ICON          = colors.HexColor('#416f86')
ACCENT        = colors.HexColor('#3e91bb')
ACCENT_2      = colors.HexColor('#c65631')
TEXT_PRIMARY  = colors.HexColor('#202224')
TEXT_MUTED    = colors.HexColor('#70777a')
SEM_SUCCESS   = colors.HexColor('#4a7e5b')
SEM_ERROR     = colors.HexColor('#8c4842')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ── Géométrie ────────────────────────────────────────────────────────────
MARGIN = 0.95 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25
MAX_KEEP = PAGE_H * 0.4

OUT_BODY = '/home/z/my-project/scripts/doc-voltrix-body.pdf'
DOC_TITLE = 'VOLTRIX bet — Dossier technique'

# ── Styles ───────────────────────────────────────────────────────────────
body_s = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=17,
                        alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY, spaceAfter=8)
lead_s = ParagraphStyle('Lead', parent=body_s, fontSize=11, leading=18,
                        textColor=TEXT_PRIMARY, spaceAfter=10)
h1_s = ParagraphStyle('H1', fontName='FreeSerif', fontSize=22, leading=27,
                      textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=4)
h2_s = ParagraphStyle('H2', fontName='FreeSerif', fontSize=15, leading=20,
                      textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
h3_s = ParagraphStyle('H3', fontName='FreeSerif', fontSize=11.5, leading=16,
                      textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=5)
bullet_s = ParagraphStyle('Bullet', parent=body_s, alignment=TA_LEFT, leftIndent=14,
                          bulletIndent=2, spaceAfter=4)
caption_s = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
                           alignment=TA_CENTER, textColor=TEXT_MUTED,
                           spaceBefore=3, spaceAfter=6)
code_s = ParagraphStyle('Code', fontName='DejaVuSans', fontSize=8.5, leading=13,
                        alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                        backColor=SECTION_BG, borderPadding=6, leftIndent=6,
                        spaceBefore=6, spaceAfter=8)
quote_s = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=10.5, leading=17,
                         leftIndent=24, textColor=TEXT_MUTED, spaceBefore=6, spaceAfter=8)
th_s = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9.5, leading=13,
                      textColor=colors.white, alignment=TA_CENTER)
td_s = ParagraphStyle('TD', fontName='FreeSerif', fontSize=9.5, leading=13,
                      textColor=TEXT_PRIMARY, alignment=TA_LEFT)
tdc_s = ParagraphStyle('TDC', parent=td_s, alignment=TA_CENTER)
stat_s = ParagraphStyle('StatBig', fontName='FreeSerif', fontSize=20, leading=24,
                        textColor=ACCENT, alignment=TA_CENTER)
statl_s = ParagraphStyle('StatLabel', fontName='FreeSerif', fontSize=8.5, leading=11,
                         textColor=TEXT_MUTED, alignment=TA_CENTER)
toc0 = ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=12, leading=22, leftIndent=8,
                      textColor=TEXT_PRIMARY)
toc1 = ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=10, leading=17, leftIndent=28,
                      textColor=TEXT_MUTED)
toc_title_s = ParagraphStyle('TOCTitle', fontName='FreeSerif', fontSize=20, leading=26,
                             textColor=TEXT_PRIMARY, spaceAfter=14)

# ── Gabarit avec TOC + numérotation en zones ────────────────────────────
STATE = {'body_start': None}

class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

ROMAN = {1: 'i', 2: 'ii', 3: 'iii', 4: 'iv', 5: 'v', 6: 'vi', 7: 'vii', 8: 'viii'}

def page_deco(canvas, doc):
    canvas.saveState()
    # En-tête : titre + filet accent
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    # Pied : auteur + numéro de page (romain pour le sommaire, arabe pour le corps)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, 'VOLTRIX bet · Outil informatif 18+')
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, str(doc.page))
    canvas.restoreState()

# ── Aides ────────────────────────────────────────────────────────────────
def safe_keep(elements):
    total = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total += h
    if total <= MAX_KEEP:
        return [KeepTogether(elements)]
    if len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def heading(text, style, level=0, body_start=False):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    if body_start:
        p.is_body_start = True
    return p

def h1(story, text, first_para=None, body_start=False):
    story.append(CondPageBreak(H1_ORPHAN))
    story.append(Spacer(1, 10))
    head = heading(text, h1_s, 0, body_start=body_start)
    rule = HRFlowable(width='100%', color=ACCENT, thickness=1.6, spaceBefore=2, spaceAfter=12)
    block = [head, rule]
    if first_para is not None:
        block.append(first_para)
    story.extend(safe_keep(block))

def h2(story, text, first=None):
    block = [heading(text, h2_s, 1)]
    if first is not None:
        block.append(first)
    story.extend(safe_keep(block))

def h3(story, text, first=None):
    block = [Paragraph('<b>%s</b>' % text, h3_s)]
    if first is not None:
        block.append(first)
    story.extend(safe_keep(block))

def P(txt, style=body_s):
    # Typographie française : jamais de tiret cadratin en début de ligne
    return Paragraph(txt.replace(' — ', ' — '), style)

def bullets(story, items):
    for it in items:
        story.append(Paragraph(it, bullet_s, bulletText='•'))
    story.append(Spacer(1, 4))

def callout(story, big, label):
    t = Table([[Paragraph('<b>%s</b>' % big, stat_s)], [Paragraph(label, statl_s)]],
              colWidths=[190])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('BOX', (0, 0), (-1, -1), 1, ACCENT),
        ('TOPPADDING', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 9),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    t.hAlign = 'CENTER'
    story.extend([Spacer(1, 10), KeepTogether(t), Spacer(1, 10)])

def callout_row(story, cells):
    """3 callouts côte à côte (métriques)."""
    inner = []
    for big, label in cells:
        t = Table([[Paragraph('<b>%s</b>' % big, stat_s)], [Paragraph(label, statl_s)]],
                  colWidths=[150])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
            ('BOX', (0, 0), (-1, -1), 1, ACCENT),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        inner.append(t)
    wrap = Table([inner], colWidths=[AVAIL_W / 3.0] * 3, hAlign='CENTER')
    wrap.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                              ('ALIGN', (0, 0), (-1, -1), 'CENTER')]))
    story.extend([Spacer(1, 10), KeepTogether(wrap), Spacer(1, 10)])

def table(story, header, rows, ratios, caption=None, fs=9.5):
    ths = ParagraphStyle('THx', parent=th_s, fontSize=fs)
    tds = ParagraphStyle('TDx', parent=td_s, fontSize=fs)
    data = [[Paragraph('<b>%s</b>' % c, ths) for c in header]]
    for r in rows:
        data.append([c if isinstance(c, Paragraph) else Paragraph(str(c), tds) for c in r])
    widths = [r * AVAIL_W for r in ratios]
    assert sum(widths) <= AVAIL_W + 0.5, 'table overflow'
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      TABLE_ROW_ODD if i % 2 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    story.append(Spacer(1, 14))
    if caption and len(rows) <= 15:
        story.extend(safe_keep([t, Spacer(1, 5), Paragraph(caption, caption_s)]))
    else:
        story.append(t)
        if caption:
            story.extend([Spacer(1, 5), Paragraph(caption, caption_s)])
    story.append(Spacer(1, 12))

def fit_image(path, max_w, max_h):
    im = PILImage.open(path)
    ow, oh = im.size
    rw = max_w / ow if ow > max_w else 1.0
    rh = max_h / oh if oh > max_h else 1.0
    r = min(rw, rh)
    return Image(path, width=ow * r, height=oh * r)

SHOT = '/home/z/my-project/download/doc-voltrix'

def figure(story, path, caption, max_w=250, max_h=440):
    img = fit_image(path, max_w, max_h)
    img.hAlign = 'CENTER'
    story.append(Spacer(1, 12))
    story.extend(safe_keep([img, Spacer(1, 5), Paragraph(caption, caption_s)]))
    story.append(Spacer(1, 10))

story = []

# ── Sommaire ─────────────────────────────────────────────────────────────
toc = TableOfContents()
toc.levelStyles = [toc0, toc1]
story.append(Paragraph('<b>Sommaire</b>', toc_title_s))
story.append(toc)
story.append(PageBreak())

# ═══════════════════════ CHAPITRE 1 ═══════════════════════
h1(story, '1. VOLTRIX bet : présentation', P(
    'VOLTRIX bet est une application web mobile-first d\'aide à la décision pour les pronostics '
    'football, écrite en français et conçue autour d\'un principe simple : afficher uniquement des '
    'probabilités calibrées et des cotes réellement obtenables. L\'application ne gère aucun argent '
    'et ne prend aucun pari : elle scanne chaque jour les matchs, calcule des probabilités de '
    'résultat par un modèle statistique propriétaire, puis transforme ces probabilités en outils '
    'concrets — un combinateur de paris avec cote cible et un conseiller de revente de coupon '
    'de type cash-out. L\'interface adopte un thème sombre premium (fond noir, accent volt '
    '#e8ff00) pensé pour un usage sur téléphone, et s\'installe comme PWA directement depuis le '
    'navigateur.', lead_s), body_start=True)

story.append(P(
    'Le produit s\'articule autour de quatre écrans complémentaires. L\'accueil présente les matchs '
    'du jour (filtrés strictement sur le jour calendaire UTC), enrichis d\'une analyse immédiate : '
    'pronostic principal, niveau de confiance et cotes du marché. Le Combinator construit des '
    'combinés optimaux à partir d\'une cote visée, en empilant les sélections les plus sûres du '
    'vivier, avec des critères de triage entièrement contrôlables par l\'utilisateur. La Vente '
    'accompagne le coupon après l\'achat : elle évalue en direct l\'offre de rachat proposée par le '
    'bookmaker et tranche — vendre ou garder. Enfin, l\'écran Précision mesure honnêtement la '
    'performance passée du modèle (taux de réussite par niveau de confiance, score de Brier), ce '
    'qui boucle la boucle entre prédictions et réalité.'))

callout_row(story, [
    ('121', 'ligues couvertes (catalogue ESPN validé)'),
    ('4', 'écrans : Accueil, Combinator, Vente, Précision'),
    ('18+', 'outil informatif — aucun argent réel'),
])

story.append(P(
    'Trois principes fondateurs guident chaque choix technique du projet. Premier principe, '
    'l\'honnêteté d\'affichage : la cote totale d\'un combiné est le produit exact des cotes '
    'affichées, les matchs affichés sont ceux du jour réel, et un échec de chargement est annoncé '
    'comme tel plutôt que masqué derrière un état vide. Deuxième principe, la calibration : les '
    'probabilités sont ancrées sur les cotes réelles du marché quand elles existent, ce qui évite '
    'les dérives classiques des modèles fermés. Troisième principe, la sobriété volontaire : '
    'chaque sélection proposée respecte un plancher de probabilité, et le moteur refuse '
    'explicitement d\'empiler des paris à 30 % de chances pour gonfler artificiellement une cote. '
    'Ces principes se retrouvent jusque dans les mentions légales de l\'interface, qui rappelle '
    'que l\'outil est informatif et destiné à un public majeur.'))

# ═══════════════════════ CHAPITRE 2 ═══════════════════════
h1(story, '2. Architecture technique', P(
    'VOLTRIX bet repose sur une pile JavaScript unifiée exécutée par Bun. Le front-end et les '
    'routes API partagent le même projet Next.js 16 (App Router) en TypeScript strict, stylé avec '
    'Tailwind CSS v4 ; la persistance passe par Prisma sur une base SQLite embarquée. Cette '
    'homogénéité simplifie le déploiement sur une seule machine : un processus Node/Next écoute '
    'sur le port 3000, compile à la volée via Turbopack en développement, et sert à la fois '
    'l\'interface et les calculs. L\'application est une PWA : le thème, les icônes et le '
    'manifeste permettent une installation sur l\'écran d\'accueil du téléphone, et la navigation '
    'par onglets (Accueil, Ligues, Vente, Précision, Profil) reste utilisable à une main.'))

h2(story, '2.1 Organisation du code', P(
    'Le code source sépare nettement les trois responsabilités du produit. Le dossier '
    '<font name="DejaVuSans">src/app</font> contient les pages (accueil, combinator, ticket, vente, '
    'précision) et les routes API ; <font name="DejaVuSans">src/lib</font> regroupe le moteur '
    'purement calculatoire (prédiction, combinatoire, probabilités live, règlement) ainsi que les '
    'adaptateurs de données ; <font name="DejaVuSans">src/components</font> porte les composants '
    'd\'interface partagés (cartes de match, barres de probabilité, navigation). Cette séparation '
    'permet de tester le moteur sans interface : les suites de tests attaquent directement les '
    'modules de <font name="DejaVuSans">src/lib</font>, ce qui a permis de corriger et de '
    're-vérifier empiriquement chaque biais de calibration documenté au chapitre 9.'))
story.append(Paragraph(
    'src/app/          pages + routes API (App Router)<br/>'
    'src/lib/          moteur : prediction.ts, combo.ts, live-prob.ts, cache.ts, espn.ts...<br/>'
    'src/components/   UI : match-card, match-detail, tab-bar, shared<br/>'
    'prisma/           schéma SQLite (pronostics, bankroll)<br/>'
    'scripts/          harnais de tests (combo, critères, live-prob, bankroll...)', code_s))

h2(story, '2.2 Routes API', P(
    'L\'interface ne calcule rien elle-même : elle consomme six routes API qui encapsulent le scan, '
    'le calcul et le règlement. Chaque route répond en JSON et met en cache son résultat serveur '
    'pour amortir les appels répétés — le TTL effectif observé est de 60 à 90 secondes, ce qui '
    'correspond à la fenêtre de fraîcheur des données ESPN tout en protégeant la source contre les '
    'rafales de requêtes. Le tableau ci-dessous résume le contrat de chaque route.'))
table(story,
      ['Route', 'Méthode', 'Rôle'],
      [
          ['/api/matches?date=AAAA-MM-JJ', 'GET', 'Scan du jour : matchs UTC stricts, ligues actives, cotes, cache LRU'],
          ['/api/predictions', 'POST', 'Analyse d\'un match : λ, probabilités, marchés, value, Kelly'],
          ['api/match/[id]', 'GET', 'Dossier complet d\'un match (forme, Elo, blessures, historique)'],
          ['/api/cashout', 'POST', 'Évaluation d\'une offre de revente jambe par jambe (live)'],
          ['/api/bankroll/resolve', 'POST', 'Règlement des pronostics (grading) et statistiques'],
          ['/api/performance', 'GET', 'Agrégation de précision bornée aux 10 derniers jours'],
      ],
      [0.34, 0.12, 0.54],
      caption='Tableau 2.1 — Contrats des routes API internes.')

h2(story, '2.3 Cache serveur et résilience', P(
    'Toutes les données distantes transitent par un store partagé sur '
    '<font name="DejaVuSans">globalThis</font>, organisé par familles de clés (scoreboards, '
    'calendriers d\'équipes, classements, blessures, météo, analyses). Ce store est un LRU borné à '
    '600 entrées avec un balayage des expirations toutes les 60 secondes ; chaque entrée porte son '
    'TTL propre et un compteur d\'évictions est journalisé régulièrement dans les logs serveur '
    '(lignes <font name="DejaVuSans">[mem]</font>). Cette borne est née d\'un incident réel : deux '
    'crashs par épuisement du tas Node (OOM) ont montré que des caches non bornés finissent par '
    'consommer les 2 Go du processus. Depuis la correction, le test de charge montre un plateau : '
    'la RSS monte transitoirement sous les salves puis retombe au niveau initial après passage du '
    'ramasse-miettes.'))
story.append(P(
    'Côté client, la résilience est traitée comme une fonctionnalité à part entière. La page '
    'd\'accueil distingue trois états : chargement (squelettes), vide réel (HTTP 200 avec zéro '
    'match — seul cas où « Aucun match trouvé » s\'affiche) et erreur (réseau, timeout ou 5xx), '
    'cette dernière affichant « Impossible de charger les matchs » avec un bouton Réessayer, deux '
    'relances automatiques en backoff et la conservation des dernières données connues derrière un '
    'bandeau de reconnexion. Ce choix répond à un bug utilisateur réel : un serveur momentanément '
    'mort faisait croire à une journée sans matchs, ce qui est inacceptable pour un outil de '
    'décision. Le même motif d\'erreur explicite a été étendu au Combinator et à l\'onglet Ligues.'))

# ═══════════════════════ CHAPITRE 3 ═══════════════════════
h1(story, '3. Sources de données : ESPN', P(
    'Toutes les données brutes proviennent d\'un unique fournisseur : les endpoints publics ESPN. '
    'Ce choix fait suite à une comparaison empirique menée avec des alternatives (Sofascore, '
    'FBref, ClubElo) : Sofascore bloque les IP de datacenter derrière Cloudflare (HTTP 403 '
    'systématique), tandis qu\'ESPN répond 200 avec un user-agent adapté et couvre l\'intégralité '
    'du besoin — calendriers et scores, cotes d\'ouverture et de clôture DraftKings, forme '
    'récente, classements, historique de deux saisons pour les Elo, compositions et blessures. Le '
    'module <font name="DejaVuSans">espn.ts</font> centralise la totalité des appels : un seul '
    'point de fetch, des en-têtes explicites (user-agent <font name="DejaVuSans">curl/8.5.0</font>), '
    'des pauses de 250 à 400 ms entre requêtes et des timeouts avec AbortController (8 s pour les '
    'payloads lourds, 6 s pour la météo).'))
table(story,
      ['Ressource ESPN', 'Contenu consommé', 'Usage'],
      [
          ['scoreboard (par ligue, par date)', 'Événements, horaires, scores, statut', 'Scan du jour, suivi live, règlement'],
          ['odds (DraftKings)', '1X2, O/U avec lignes, ouverture/clôture', 'Ancrage du modèle, cotes réelles'],
          ['teams schedule', 'Matchs récents par équipe', 'Forme, GF/GA par contexte'],
          ['standings', 'Rang, points, groupe', 'Contexte de classement'],
          ['history 2 saisons', 'Résultats passés', 'Elo par équipe'],
          ['injuries /Athlete', 'Joueurs absents et statut', 'Multiplicateur de λ'],
      ],
      [0.30, 0.38, 0.32],
      caption='Tableau 3.1 — Ressources ESPN consommées et leur usage dans le moteur.')

h2(story, '3.1 Le problème des journées et le filtre UTC', P(
    'ESPN groupe ses scoreboards par journée sportive américaine (fuseau US Eastern), ce qui '
    'déborde largement du jour calendaire européen : un match de MLS de nuit apparaît sur la '
    'feuille d\'une autre date. Pour garantir que « Aujourd\'hui » ne montre que les matchs '
    'réellement joués ce jour, la route de scan applique un filtre strict en temps UTC : chaque '
    'événement doit satisfaire '
    '<font name="DejaVuSans">t ≥ JJ 00:00 UTC</font> et '
    '<font name="DejaVuSans">t &lt; JJ+1 00:00 UTC</font>. Ce garde-fou, protégé par des tests de '
    'non-régression, est la réponse à un bug signalé par les utilisateurs : des matchs de demain '
    'dans « Aujourd\'hui » et inversement. Il a un corollaire : les matchs qui se jouent entre '
    '00 h et 04 h UTC existent sur la feuille de la veille côté ESPN. Le règlement et l\'analyse '
    'live appliquent donc un repli systématique sur la feuille J−1 quand un identifiant de match '
    'est introuvable sur la feuille du jour — ce repli a été validé de bout en bout sur des matchs '
    'MLS nocturnes réels, réglés avec leurs vrais scores.'))

h2(story, '3.2 Fraîcheur, volume et catalogue', P(
    'Le scan d\'une journée parcourt les 121 ligues du catalogue par ordre de priorité fixe, en '
    'concurrence limitée, et ne conserve que les ligues ayant au moins un événement dans la fenêtre '
    'UTC du jour. Une journée de semaine type renvoie de 15 à 60 matchs ; un samedi de compétitions '
    'peut dépasser 200 matchs, analyse comprise en quelques secondes grâce au cache. Le catalogue '
    'couvre les cinq grands championnats européens, les coupes continentales, l\'Amérique du Sud, '
    'l\'Asie et un ensemble croissant de divisions secondaires — chaque code ESPN du catalogue a '
    'été validé empiriquement (HTTP 200 et payload exploitable) avant intégration. Les réponses du '
    'scan excluent volontairement toute complétion par les jours suivants : si le jour offre 15 '
    'matchs, l\'application en affiche 15, et non un pool gonflé par les journées voisines.'))

# ═══════════════════════ CHAPITRE 4 ═══════════════════════
h1(story, '4. Moteur de prédiction : de ESPN aux probabilités', P(
    'Le cœur de VOLTRIX bet est un pipeline qui transforme des statistiques brutes en probabilités '
    'de match calibrées. Le principe directeur est le retrait vers la moyenne : chaque composante '
    'statistique est normalisée, bornée et ancrée sur les références du football professionnel, si '
    'bien qu\'un match entre équipes moyennes produit un total de buts attendus autour de 2,7 — '
    'conformément au marché — plutôt qu\'un λ aberrant. Ce chapitre détaille chaque étape du '
    'pipeline, dans l\'ordre d\'exécution du code.'))

story.append(fit_image('/home/z/my-project/download/doc-voltrix/pipeline.png', AVAIL_W, 300))
story.extend([Spacer(1, 5), Paragraph(
    'Figure 4.1 — Pipeline de calcul : de la donnée ESPN aux produits utilisateur.', caption_s)])
story.append(Spacer(1, 8))

h2(story, '4.1 Normalisation et shrinkage des forces d\'attaque et de défense', P(
    'Pour chaque équipe, le module extrait les buts marqués et encaissés par match (GF/GA) dans le '
    'contexte exact du match à venir : une équipe jouant à domicile est jugée sur ses matchs à '
    'domicile, une équipe à l\'extérieur sur ses matchs à l\'extérieur. Ces ratios sont ensuite '
    'normalisés par les références empiriques du football professionnel — 1,52 but marqué par '
    'match à domicile, 1,22 à l\'extérieur, 1,37 pour la moyenne des encaissements — ce qui donne '
    'un ratio neutre à 1,0 pour une équipe moyenne. Chaque ratio est enfin compressé par un '
    'shrinkage de type empirical Bayes d\'intensité n/(n+K) avec K = 10 : un petit échantillon '
    'est fortement tiré vers la moyenne, un grand échantillon conserve sa valeur observée. '
    'Formellement, pour un ratio r observé sur n matchs :'))
story.append(Paragraph(
    'r<super>*</super> = (n / (n + 10)) × r + (10 / (n + 10)) × 1,0', code_s))
story.append(P(
    'Cette étape est la réponse directe au premier biais diagnostiqué du moteur : en coupe, une '
    'équipe n\'ayant qu\'un ou deux matchs dans sa compétition produisait des ratios extrêmes '
    '(0,45 à 7,5 buts attendus) sans garde-fou. Le shrinkage rend mathématiquement impossible ce '
    'type d\'explosion : avec n = 2, le poids de l\'observation n\'est plus que de 16,7 %. Le '
    'contexte du match est également corrigé pour l\'équipe extérieure — ses buts marqués à '
    'l\'extérieur alimentent son attaque, et non ceux du match lui-même, une inversion de champs '
    'qui avait faussé les premières versions.'))

h2(story, '4.2 Étape Elo : redistribution préservant le total', P(
    'Les Elo des deux équipes (calculés sur l\'historique des deux saisons ESPN, avec avantage du '
    'terrain compté une seule fois) convertissent l\'écart de niveau en attente de résultat via la '
    'formule logistique classique, puis modulent les buts attendus. La contrainte clé est la '
    'conservation du total : l\'étape Elo redistribue la force relative entre λ domicile et λ '
    'extérieur sans jamais gonfler leur somme — un favori voit son λ augmenter au détriment de '
    'celui de son adversaire, avec un clamp de ±250 points d\'écart effectif. Avant correction, '
    'l\'avantage du terrain était compté en double (déjà inclus dans les références 1,52/1,22) et '
    'le signe du bonus était inversé dans la conversion logistique : à Elo égal, l\'équipe '
    'domicile était désavantagée. Ces deux défauts ont été corrigés et verrouillés par un harnais '
    'de 20 vérifications, dont le cas canonique : à Elo égal, probabilité domicile ≈ 46,6 % '
    'contre ≈ 28,1 % pour l\'extérieur, le nul prenant le reste.'))
story.append(Paragraph(
    'E<sub>dom</sub> = 1 / (1 + 10<super>((R<sub>ext</sub> + ADV − R<sub>dom</sub>) / 400)</super>)'
    '   avec ADV ≈ 65 points, R\' = R + K(S − E)', code_s))

h2(story, '4.3 Blessures et bornes finales', P(
    'Les absents déclarés ESPN modulent les buts attendus de l\'équipe concernée, avec un seuil '
    'd\'entrée volontairement haut : les deux premières indisponibilités ne comptent pas — les '
    'listes ESPN incluent en effet des joueurs de rotation — puis chaque absent supplémentaire '
    'retire 2 % par joueur, avec un plancher à 0,92 (8 % de baisse maximum). Le λ final de chaque '
    'équipe est enfin borné dans un couloir réaliste : [0,30 ; 3,80] pour le domicile et '
    '[0,25 ; 3,40] pour l\'extérieur. Ces bornes garantissent qu\'aucun marché dérivé ne peut '
    'produire une probabilité absurde (un « Moins de 2,5 buts » à 99 % n\'a plus jamais été émis '
    'depuis la correction, alors que le biais pré-correction en produisait régulièrement).'))

h2(story, '4.4 Calibration sur les marchés réels', P(
    'Quand ESPN publie une ligne Over/Under avec cotes pour le match, le module compare le total '
    'attendu du modèle au λ implicite du marché. Ce λ implicite est obtenu par dé-marging : les '
    'deux cotes du marché sont converties en probabilités brutes, la marge du bookmaker est '
    'retirée en normalisant leur somme à 1, puis le λ est inversé depuis la loi de Poisson sur la '
    'ligne proposée. Le total du modèle est ensuite ré-ancré (calibrateTotals) vers le λ marché '
    'dans une fenêtre bornée — le marché reste la référence, mais une divergence modérée du modèle '
    'est précisément ce qui crée les value bets détectés au chapitre suivant. Sur l\'échantillon '
    'de contrôle de 72 matchs avec ligne réelle, la médiane du rapport λ modèle / λ marché est de '
    '0,90 et 26 matchs sur 30 restent dans une bande de ±20 % après corrections.'))
story.append(Paragraph(
    'p<sub>i</sub><super>démargée</super> = p<sub>i</sub> / (p<sub>1</sub> + p<sub>2</sub>)'
    '   puis inversion Poisson → λ<sub>marché</sub>', code_s))

h2(story, '4.5 Matrice de Poisson et marchés dérivés', P(
    'Les buts attendus des deux équipes alimentent une matrice de Poisson 16 × 16 : chaque cellule '
    '(i, j) porte la probabilité du score final i-j, calculée indépendamment par équipe puis '
    'multipliée (hypothèse d\'indépendance des attaques). Tous les marchés proposés par '
    'l\'application découlent de cette matrice par simple sommation de cellules : 1X2 (somme du '
    'triangle inférieur, diagonale, triangle supérieur), double chance (réunion de deux '
    'issues), Over/Under par ligne (somme des cellules au-delà de la ligne), BTTS (produit des '
    'queues non nulles) et premier buteur d\'un côté ou de l\'autre. La loi de Poisson utilisée '
    'est la formulation standard :'))
story.append(Paragraph(
    'P(X = k) = e<super>−λ</super> × λ<super>k</super> / k!   ;   '
    'P(Moins de 2,5) = Σ<sub>k=0..2</sub> P(k)   ;   somme des marches firstToScore ≡ 1,000', code_s))
story.append(P(
    'La décomposition firstToScore (qui marque en premier : domicile, extérieur, personne) est '
    'testée par un harnais dédié sur une grille de λ allant de 0,1 à 4,0 : la somme des trois '
    'probabilités vaut exactement 1,000, y compris dans le cas dégénéré λ = 0 où « personne ne '
    'marque » vaut 1. Ce test existait pour une raison précise : la version initiale sommait à '
    '1 + e<super>−λ</super>, soit environ 1,06, et cette incohérence se propageait aux marchés '
    'composés. Chaque correction du moteur est ainsi accompagnée de son harnais de non-régression, '
    'et l\'ensemble des suites (76 tests combinatoires, 46 tests de remplacement, 25 tests de '
    'probabilités live, 61 tests de bankroll, 36 tests de règlement) est relancé à chaque '
    'modification.'))

h2(story, '4.6 De la probabilité à la cote : value bets et Kelly', P(
    'La cote juste d\'un marché est simplement l\'inverse de sa probabilité, '
    '<font name="DejaVuSans">cote = 1/p</font> : un événement à 40 % vaut 2,50. Un marché devient '
    'un value bet lorsque la cote réelle du bookmaker dépasse la cote juste du modèle — l\'écart '
    'en pourcentage (edge) est affiché sur la fiche de chaque match avec la comparaison « Marché '
    'vs Modèle ». La mise conseillée suit le critère de Kelly fractionné, plafonné à 10 % du '
    'capital pour refléter l\'incertitude résiduelle du modèle :'))
story.append(Paragraph(
    'f<super>*</super> = (b × p − q) / b   avec b = cote − 1, q = 1 − p ;   mise = min(f<super>*</super>, 0,10) × capital', code_s))
story.append(P(
    'Deux garde-fous complètent le dispositif. D\'une part, les cotes « estimées » — celles que le '
    'modèle déduit de ses probabilités quand aucune cote réelle n\'existe — sont marquées comme '
    'telles dans le vivier et exclues par défaut des combinés, puisque aucune d\'entre elles '
    'n\'est obtenable chez un bookmaker ; le critère « cotes réelles uniquement » est activé '
    'd\'usine. D\'autre part, les lignes Over/Under non couvertes par le modèle (par exemple une '
    'ligne 4,5 quand le modèle n\'évalue que 1,5/2,5/3,5) affichent un tiret plutôt qu\'un zéro, '
    'pour ne jamais présenter une probabilité modèle inexistante comme une certitude nulle.'))

# ═══════════════════════ CHAPITRE 5 ═══════════════════════
h1(story, '5. Le Combinator : construire un combiné à cote cible', P(
    'Le Combinator répond à une question difficile : « je vise une cote de 10, quelle est la '
    'meilleure combinaison de paris que je peux empiler ? ». L\'algorithme part du vivier du '
    'jour — l\'ensemble des marchés analysés pour chaque match — puis recherche une combinaison '
    'dont le produit de cotes atteint la cible en maximisant la probabilité de gain du produit. '
    'La contrainte d\'or est structurelle : la cote totale affichée est le produit exact des '
    'cotes affichées de chaque jambe, sans arrangement ni arrondi flatteur. Un combiné ×10,14 '
    'affiché est, chez le bookmaker, un combiné ×10,14.'))

h2(story, '5.1 Critères de triage', P(
    'L\'utilisateur filtre le vivier avant la recherche via un panneau de critères persistés : '
    'marchés autorisés (1X2, double chance, Over/Under, BTTS), niveau de confiance minimal du '
    'modèle, exclusion des cotes estimées (activée par défaut, voir chapitre 4.6) et exclusion de '
    'ligues entières. Les critères s\'appliquent à la génération initiale ET aux échanges manuels '
    'ultérieurs : une jambe remplacée hérite des mêmes contraintes. Le tableau ci-dessous résume '
    'les critères et leurs valeurs par défaut.'))
table(story,
      ['Critère', 'Défaut', 'Effet sur le vivier'],
      [
          ['Marchés autorisés', 'tous', 'Restreint aux types de marchés cochés'],
          ['Confiance minimale', 'aucune', 'Écarte les sélections sous le niveau choisi (1 à 4 étoiles)'],
          ['Cotes réelles uniquement', 'activé', 'Exclut les cotes estimées non obtenables au guichet'],
          ['Ligues exclues', 'aucune', 'Retire du vivier les ligues décochées'],
      ],
      [0.30, 0.16, 0.54],
      caption='Tableau 5.1 — Critères de triage du Combinator et valeurs d\'usine.')

h2(story, '5.2 Réparation vers la cible et remplacement même-match', P(
    'Deux mécanismes garantissent que le combiné reste cohérent après manipulation. La réparation '
    'automatique (repairToTarget) s\'applique quand un échange manuel fait tomber la cote sous la '
    'cible : le moteur procède à des échanges un-pour-un à probabilité maximale, sous les mêmes '
    'contraintes, jusqu\'à rétablir la cible — ou affiche explicitement un badge « sous '
    'l\'objectif » avec la mention de la cote réelle. Le remplacement même-match, ajouté à la '
    'demande des utilisateurs, permet de changer de pari sur un match sans changer de match : la '
    'feuille d\'échange liste tous les candidats du même matchId, regroupés par famille de marché '
    '(Résultat 1X2, Double chance, Buts Over/Under, BTTS), avec cote réelle, source et confiance ; '
    'la sélection est exclusive avec les échanges inter-matchs et l\'aperçu affiche la cote '
    'totale avant/après. L\'exemple réel ci-dessous illustre le flux complet.'))
story.append(P(
    'Exemple chiffré (capture du chapitre 8) : un combiné ×3,06 = 2,00 × 1,53 contient la jambe '
    '« Slavia Prague ou Nul » (double chance à 2,00). L\'utilisateur ouvre la feuille d\'échange, '
    'choisit « Victoire Slavia Prague » (1X2, cote 2,70, même match) : la nouvelle cote totale '
    'est 2,00 × 2,70 = 5,40, affichée avant validation, probabilité recalculée à la baisse. Dans '
    'le cas inverse — un remplacement qui fait passer sous la cible — la réparation automatique '
    'relance la recherche et ramène le produit au niveau visé. Chaque étape est annulable (undo) '
    'et le ticket final transférable vers la Vente en un tap.'))

# ═══════════════════════ CHAPITRE 6 ═══════════════════════
h1(story, '6. La Vente : conseiller de revente de coupon', P(
    'Certains bookmakers proposent de racheter un coupon avant la fin de ses matchs : l\'utilisateur '
    'qui a misé 100 peut se voir offrir 25 pour céder son ticket. La Vente répond à la question '
    '« dois-je vendre ? » par une analyse probabiliste en direct plutôt qu\'à l\'intuition. Le '
    'coupon est transféré depuis le Combinator avec sa mise réellement engagée et sa devise (16 '
    'devises gérées, formatage Intl) ; à tout moment, l\'utilisateur saisit l\'offre du bookmaker '
    'et lance l\'analyse.'))

h2(story, '6.1 Calcul de la valeur juste', P(
    'Pour chaque jambe du coupon, la route /api/cashout consulte l\'état ESPN réel du match. Un '
    'match terminé est noté gagné ou perdu par le module de grading partagé avec le règlement. Un '
    'match en cours est re-probabilisé par le module live-prob : le score courant est retiré de la '
    'distribution ( convolution par le score final restant), le λ restant est proportionnel à la '
    'fraction de temps restant — l\'horloge ESPN (minute, mi-temps) prime sur le temps mural — et '
    'la probabilité de la sélection est recalculée sur cette base. Un match pas encore commencé '
    'conserve sa probabilité initiale, en dégradation propre si la donnée manque. La valeur juste '
    'du coupon est alors :'))
story.append(Paragraph(
    'V = mise × cote × Π p<sub>j</sub> (jambes encore vivantes, gagnées = 1)', code_s))
story.append(P(
    'L\'offre du bookmaker est comparée à V avec trois zones de décision : vendre si l\'offre '
    'dépasse la valeur juste, zone grise si l\'offre en couvre au moins 85 % (l\'utilisateur '
    'arbitre alors entre certitude et espérance), garder sinon. Le verdict s\'accompagne d\'un '
    'message explicite — « l\'offre est 74 % sous sa valeur estimée » — et du détail jambe par '
    'jambe (score, horloge, delta de probabilité). L\'exemple réel de la capture : coupon à mise '
    '100, cote 10,14, quatre matchs pas encore commencés, offre de 25 — valeur juste ≈ 96, verdict '
    'GARDER. Les coupons vendus sont archivés avec leur prix réel et le bilan ± est suivi par '
    'devise. Un garde-fou limite à 50 le nombre de jambes d\'une requête pour éviter tout fan-out '
    'excessif vers ESPN.'))

# ═══════════════════════ CHAPITRE 7 ═══════════════════════
h1(story, '7. Précision et règlement des pronostics', P(
    'Un modèle sans mesure de performance n\'est qu\'une opinion. VOLTRIX bet règle '
    'automatiquement ses pronostics passés et expose les statistiques de réussite dans l\'écran '
    'Précision. Le règlement s\'appuie sur un module de grading unique (grade.ts) partagé entre '
    'la Vente et la route de règlement : un même événement est noté une seule fois, avec repli '
    'systématique sur la feuille ESPN de la veille pour les matchs nocturnes (chapitre 3.1). La '
    'route /api/performance agrège les pronostics des 10 derniers jours — borne ajoutée pour '
    'garantir des temps de réponse de l\'ordre de 150 ms — et calcule par niveau de confiance le '
    'taux de réussite observé.'))

story.append(P(
    'L\'indicateur central est le score de Brier, moyenne des carrés des écarts entre probabilité '
    'annoncée et issue observée (0 = parfait, 0,25 = hasard sur un binaire). Les valeurs observées '
    'en production tournent autour de 0,25-0,26 sur l\'ensemble des pronostics, ce qui est '
    'cohérent avec un modèle calibré sur des événements incertains ; l\'écran distingue '
    'explicitement les bandes de confiance où le modèle est le plus fiable. Cette transparence '
    'est un choix produit : l\'utilisateur voit où le modèle se trompe, pas seulement où il '
    'réussit. Les pronostics déjà résolus ne sont jamais réécrits par une nouvelle analyse — '
    'correction apportée après observation d\'un upsert qui déformait a posteriori les '
    'statistiques historiques.'))

# ═══════════════════════ CHAPITRE 8 ═══════════════════════
h1(story, '8. Guide écran par écran', P(
    'Ce chapitre illustre le parcours utilisateur complet avec des captures réelles de '
    'l\'application (viewport 390 × 844, données du jour). Pour chaque écran : son rôle, les '
    'éléments clés et le geste principal. Les captures sont présentées dans l\'ordre du parcours '
    'type : consulter le jour, analyser un match, construire un combiné, ajuster une jambe, '
    'transférer le ticket, évaluer une offre de revente, puis vérifier la précision du modèle.'))

h2(story, '8.1 Accueil — le jour réel')
story.append(P(
    'L\'accueil s\'ouvre sur la journée du jour : une rangée de chips de dates (Hier, '
    'Aujourd\'hui, Demain, puis la semaine), une rangée de chips de ligues avec compteurs, et la '
    'liste des matchs filtrée strictement sur le jour UTC. Chaque carte porte les équipes, '
    'l\'heure, l\'épine de ligue, le pronostic principal du modèle et son pourcentage ; les '
    'matchs en direct affichent leur score. Le bouton Rafraîchir force un re-scan ; en cas de '
    'panne réseau, l\'écran d\'erreur propose Réessayer au lieu d\'un faux état vide.'))
figure(story, f'{SHOT}/01-accueil.png', 'Capture 8.1 — Accueil : header, chips de dates, cote cible du jour.')

h2(story, '8.2 Liste de matchs analysés')
story.append(P(
    'Le défilement fait apparaître les cartes de matchs du jour, chacune enrichie de l\'analyse : '
    'pronostic, barre de probabilité, badge de confiance. Un samedi de compétitions peut afficher '
    'plus de 200 matchs analysés — tous du jour, sans complétion par les jours voisins. Chaque '
    'carte est un point d\'entrée vers le dossier complet du match.'))
figure(story, f'{SHOT}/02-accueil-cartes.png', 'Capture 8.2 — Cartes de matchs avec pronostics et confiance.')

h2(story, '8.3 Dossier de match')
story.append(P(
    'Un tap sur une carte ouvre le dossier du match : en-tête avec compétition, rangs des équipes '
    'et stade, bannière « Confiance du modèle », puis les pronostics par marché avec la '
    'comparaison Marché vs Modèle (l\'edge en pourcentage signale les value bets). Les lignes '
    'non couvertes par le modèle affichent un tiret — jamais un faux 0 %. En direct, le score et '
    'l\'horloge ESPN alimentent aussi la Vente.'))
figure(story, f'{SHOT}/03-detail-match.png', 'Capture 8.3 — Dossier : Palmeiras − São Paulo en direct.')

h2(story, '8.4 Pronostics et cotes du match')
story.append(P(
    'La suite du dossier détaille chaque marché : probabilité modèle, cote juste 1/p, cote du '
    'marché et écart. C\'est l\'écran de référence pour juger un pari isolé avant de l\'empiler '
    'dans un combiné — le modèle y affiche à la fois sa force (probabilités calibrées) et ses '
    'limites (tiret sur les lignes non couvertes).'))
figure(story, f'{SHOT}/04-detail-pronos.png', 'Capture 8.4 — Marchés du match : Marché vs Modèle, edge.')

h2(story, '8.5 Combinator — formulaire et critères')
story.append(P(
    'Le Combinator demande trois entrées : la cote cible (champ libre ou pastilles ×2 à ×50), le '
    'profil de risque (Prudent, Équilibré, Agressif — qui fixe le plancher de probabilité et le '
    'plafond de cote par jambe) et, via le panneau Critères, les marchés autorisés, la confiance '
    'minimale, l\'exclusion des cotes estimées et les ligues exclues. Le jour analysé se change '
    'par chips (Aujourd\'hui / Demain).'))
figure(story, f'{SHOT}/05-combo-form.png', 'Capture 8.5 — Formulaire : cote cible, profil de risque.')

h2(story, '8.6 Combinator — résultat à cote exacte')
story.append(P(
    'Après génération, le ticket affiche chaque jambe (match, marché, cote, source, confiance) et '
    'la cote totale — produit exact des jambes. L\'exemple du jour : quatre jambes toutes à cote '
    'réelle, total ×10,14, probabilité du combiné et mise Kelly conseillée affichées. Un badge '
    '« sous l\'objectif » apparaîtrait explicitement si un échange faisait tomber le produit sous '
    'la cible avant réparation.'))
figure(story, f'{SHOT}/07-combo-result.png', 'Capture 8.6 — Combiné généré : 4 jambes, cote totale exacte.')

h2(story, '8.7 Remplacement par un pari du même match')
story.append(P(
    'Le bouton d\'échange d\'une jambe ouvre la feuille de remplacement : section « Autres paris '
    'du même match » regroupée par famille (Résultat 1X2, Double chance, Buts Over/Under, BTTS), '
    'chacune avec cote réelle et confiance ; puis, en dessous, les candidats d\'autres matchs. '
    'Les deux sections sont exclusives — jamais deux jambes du même match — et l\'aperçu montre '
    'la cote totale avant/après avant validation du remplacement.'))
figure(story, f'{SHOT}/08-meme-match.png', 'Capture 8.7 — Feuille d\'échange : alternatives du même match.')

h2(story, '8.8 Ticket plein écran et transfert')
story.append(P(
    'Le ticket en plein écran détaille le combiné (noms complets, marchés, cotes, probabilité '
    'multipliée des jambes indépendantes) et porte le bouton « Transférer vers la Vente ». Le '
    'transfert demande la mise réellement engagée et la devise — c\'est cette mise qui servira de '
    'base au calcul de la valeur juste du coupon.'))

h2(story, '8.9 Vente — évaluer une offre de rachat')
story.append(P(
    'Sur l\'écran Vente, le coupon en cours expose son gain potentiel et le bouton « Évaluer une '
    'offre ». L\'utilisateur saisit le prix proposé par le bookmaker (25 dans la capture), lance '
    'l\'analyse : chaque jambe est re-probabilisée selon son état réel ESPN, la valeur juste est '
    'affichée en face de l\'offre, et le verdict tranché — ici GARDER, l\'offre étant 74 % sous '
    'la valeur estimée. Les coupons vendus passent en section VENDUS avec le bilan ± par devise.'))
figure(story, f'{SHOT}/12-vente-eval.png', 'Capture 8.8 — Verdict : offre 25 vs valeur juste, GARDER.')

h2(story, '8.10 Précision — le modèle rend des comptes')
story.append(P(
    'L\'écran Précision agrège les pronostics réglés : taux de réussite global et par bande de '
    'confiance, score de Brier, historique des 10 derniers jours. C\'est l\'outil d\'audit '
    'permanent du modèle — et le contrepoint honnête de ses réussites.'))
figure(story, f'{SHOT}/13-precision.png', 'Capture 8.9 — Précision : réussite par confiance, Brier.')

# ═══════════════════════ CHAPITRE 9 ═══════════════════════
h1(story, '9. Qualité, limites et évolution', P(
    'La qualité du projet repose sur un triptyque : suites de tests unitaires sur le moteur, '
    'validation croisée par sous-agents sur chaque évolution, et parcours E2E automatisés sur '
    'viewport mobile. Les suites couvrent le moteur combinatoire (76 tests dont l\'invariant de '
    'produit), les critères de triage (25), les probabilités live (25), la bankroll (61) et le '
    'règlement (36, concordance totale avec le grading partagé), auxquels s\'ajoutent les 46 '
    'tests du remplacement même-match et les harnais de biais (Elo, λ, firstToScore). Le type-checking '
    'TypeScript et le lint passent sans erreur sur l\'ensemble du code source.'))
table(story,
      ['Domaine', 'Suite', 'Checks'],
      [
          ['Moteur combinatoire', 'test-combo + invariant', '76 + 756'],
          ['Remplacement même-match', 'test-same-match-swap', '46'],
          ['Critères de triage', 'test-criteria', '25'],
          ['Probabilités live', 'test-live-prob', '25'],
          ['Bankroll et règlement', 'bankroll + resolve-api', '61 + 36'],
      ],
      [0.38, 0.38, 0.24],
      caption='Tableau 9.1 — Suites de tests du moteur et nombre de vérifications.')

story.append(P(
    'Les corrections majeures documentées au fil des itérations sont autant de leçons d\''
    'ingénierie : filtre strict des journées UTC contre les matchs déplacés, signe de l\'avantage '
    'Elo vérifié mathématiquement et empiriquement, repli J−1 pour le règlement des matchs '
    'nocturnes, en-têtes user-agent explicites contre les 403 en production, cotes réelles par '
    'défaut dans les combinés, et caches bornés après deux crashs mémoire réels. Chacune de ces '
    'corrections est protégée par son test de non-régression et documentée dans le journal de '
    'travail du projet.'))

story.append(P(
    'Les limites sont assumées et affichées. Le modèle repose sur une seule source de données : '
    'une indisponibilité ESPN dégrade le scan (avec cache et replis, mais jamais d\'invention). '
    'Les probabilités sont des estimations calibrées, pas des certitudes — un verdict GARDER de '
    'la Vente est une espérance mathématique, pas une prédiction du futur ; l\'interface le '
    'rappelle sur chaque écran d\'analyse. L\'hypothèse d\'indépendance des attaques dans la '
    'matrice de Poisson reste une simplification classique. Enfin, l\'outil ne gère aucun argent '
    'réel et s\'adresse à un public majeur : la mise Kelly est un conseil arithmétique, pas une '
    'incitation. Les pistes d\'évolution identifiées sont l\'extension du catalogue de ligues '
    '(validation empirique par lots), l\'analyse live temps réel pour le suivi des matchs en '
    'cours depuis l\'accueil, et l\'enrichissement du conseiller de revente avec l\'historique '
    'des offres observées par bookmaker.'))

# ── Construction ─────────────────────────────────────────────────────────
doc = TocDocTemplate(
    OUT_BODY, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN, bottomMargin=MARGIN,
    title=DOC_TITLE, author='Z.ai', creator='Z.ai',
    subject='Dossier technique de l\'application VOLTRIX bet',
)
doc.multiBuild(story, onFirstPage=page_deco, onLaterPages=page_deco)
print('body OK:', OUT_BODY)

# ── Fusion couverture + corps ────────────────────────────────────────────
from pypdf import PdfReader, PdfWriter
A4_W, A4_H = 595.28, 841.89

def normalize(page):
    b = page.mediabox
    w, h = float(b.width), float(b.height)
    if abs(w - A4_W) > 0.1 or abs(h - A4_H) > 0.1:
        page.scale_to(A4_W, A4_H)
    return page

FINAL = '/home/z/my-project/download/VOLTRIX-bet-Dossier-technique.pdf'
writer = PdfWriter()
writer.add_page(normalize(PdfReader('/home/z/my-project/scripts/doc-voltrix-cover.pdf').pages[0]))
for pg in PdfReader(OUT_BODY).pages:
    writer.add_page(normalize(pg))
writer.add_metadata({'/Title': DOC_TITLE, '/Author': 'Z.ai', '/Creator': 'Z.ai',
                     '/Subject': "Dossier technique de l'application VOLTRIX bet"})
with open(FINAL, 'wb') as f:
    writer.write(f)
print('final OK:', FINAL, len(writer.pages), 'pages')
