# -*- coding: utf-8 -*-
"""Génère le corps du dossier technique VOLTRIX bet (ReportLab, TOC auto)."""
import os, sys, hashlib

PDF_SKILL = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(PDF_SKILL, 'scripts'))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, Image, KeepTogether, CondPageBreak,
                                HRFlowable)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from PIL import Image as PILImage

# ── Polices ──────────────────────────────────────────────────────────────
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#eff0f1')
SECTION_BG    = colors.HexColor('#edeeee')
CARD_BG       = colors.HexColor('#e7e9ea')
TABLE_STRIPE  = colors.HexColor('#eeeff0')
HEADER_FILL   = colors.HexColor('#3d5059')
COVER_BLOCK   = colors.HexColor('#506671')
BORDER        = colors.HexColor('#aab6bc')
ICON          = colors.HexColor('#416f86')
ACCENT        = colors.HexColor('#3e91bb')
ACCENT_2      = colors.HexColor('#c65631')
TEXT_PRIMARY  = colors.HexColor('#202224')
TEXT_MUTED    = colors.HexColor('#70777a')
SEM_SUCCESS   = colors.HexColor('#4a7e5b')
SEM_ERROR     = colors.HexColor('#8c4842')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ── Géométrie ────────────────────────────────────────────────────────────
MARGIN = 0.95 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25
MAX_KEEP = PAGE_H * 0.4

OUT_BODY = '/home/z/my-project/scripts/doc-voltrix-body.pdf'
DOC_TITLE = 'VOLTRIX bet — Dossier technique'

# ── Styles ───────────────────────────────────────────────────────────────
body_s = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=17,
                        alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY, spaceAfter=8)
lead_s = ParagraphStyle('Lead', parent=body_s, fontSize=11, leading=18,
                        textColor=TEXT_PRIMARY, spaceAfter=10)
h1_s = ParagraphStyle('H1', fontName='FreeSerif', fontSize=22, leading=27,
                      textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=4)
h2_s = ParagraphStyle('H2', fontName='FreeSerif', fontSize=15, leading=20,
                      textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
h3_s = ParagraphStyle('H3', fontName='FreeSerif', fontSize=11.5, leading=16,
                      textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=5)
bullet_s = ParagraphStyle('Bullet', parent=body_s, alignment=TA_LEFT, leftIndent=14,
                          bulletIndent=2, spaceAfter=4)
caption_s = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
                           alignment=TA_CENTER, textColor=TEXT_MUTED,
                           spaceBefore=3, spaceAfter=6)
code_s = ParagraphStyle('Code', fontName='DejaVuSans', fontSize=8.5, leading=13,
                        alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                        backColor=SECTION_BG, borderPadding=6, leftIndent=6,
                        spaceBefore=6, spaceAfter=8)
quote_s = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=10.5, leading=17,
                         leftIndent=24, textColor=TEXT_MUTED, spaceBefore=6, spaceAfter=8)
th_s = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9.5, leading=13,
                      textColor=colors.white, alignment=TA_CENTER)
td_s = ParagraphStyle('TD', fontName='FreeSerif', fontSize=9.5, leading=13,
                      textColor=TEXT_PRIMARY, alignment=TA_LEFT)
tdc_s = ParagraphStyle('TDC', parent=td_s, alignment=TA_CENTER)
stat_s = ParagraphStyle('StatBig', fontName='FreeSerif', fontSize=20, leading=24,
                        textColor=ACCENT, alignment=TA_CENTER)
statl_s = ParagraphStyle('StatLabel', fontName='FreeSerif', fontSize=8.5, leading=11,
                         textColor=TEXT_MUTED, alignment=TA_CENTER)
toc0 = ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=12, leading=22, leftIndent=8,
                      textColor=TEXT_PRIMARY)
toc1 = ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=10, leading=17, leftIndent=28,
                      textColor=TEXT_MUTED)
toc_title_s = ParagraphStyle('TOCTitle', fontName='FreeSerif', fontSize=20, leading=26,
                             textColor=TEXT_PRIMARY, spaceAfter=14)

# ── Gabarit avec TOC + numérotation en zones ────────────────────────────
STATE = {'body_start': None}

class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

ROMAN = {1: 'i', 2: 'ii', 3: 'iii', 4: 'iv', 5: 'v', 6: 'vi', 7: 'vii', 8: 'viii'}

def page_deco(canvas, doc):
    canvas.saveState()
    # En-tête : titre + filet accent
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    # Pied : auteur + numéro de page (romain pour le sommaire, arabe pour le corps)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, 'VOLTRIX bet · Outil informatif 18+')
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, str(doc.page))
    canvas.restoreState()

# ── Aides ────────────────────────────────────────────────────────────────
def safe_keep(elements):
    total = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total += h
    if total <= MAX_KEEP:
        return [KeepTogether(elements)]
    if len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def heading(text, style, level=0, body_start=False):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    if body_start:
        p.is_body_start = True
    return p

def h1(story, text, first_para=None, body_start=False):
    story.append(CondPageBreak(H1_ORPHAN))
    story.append(Spacer(1, 10))
    head = heading(text, h1_s, 0, body_start=body_start)
    rule = HRFlowable(width='100%', color=ACCENT, thickness=1.6, spaceBefore=2, spaceAfter=12)
    block = [head, rule]
    if first_para is not None:
        block.append(first_para)
    story.extend(safe_keep(block))

def h2(story, text, first=None):
    block = [heading(text, h2_s, 1)]
    if first is not None:
        block.append(first)
    story.extend(safe_keep(block))

def h3(story, text, first=None):
    block = [Paragraph('<b>%s</b>' % text, h3_s)]
    if first is not None:
        block.append(first)
    story.extend(safe_keep(block))

def P(txt, style=body_s):
    # Typographie française : jamais de tiret cadratin en début de ligne
    return Paragraph(txt.replace(' — ', ' — '), style)

def bullets(story, items):
    for it in items:
        story.append(Paragraph(it, bullet_s, bulletText='•'))
    story.append(Spacer(1, 4))

def callout(story, big, label):
    t = Table([[Paragraph('<b>%s</b>' % big, stat_s)], [Paragraph(label, statl_s)]],
              colWidths=[190])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('BOX', (0, 0), (-1, -1), 1, ACCENT),
        ('TOPPADDING', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 9),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    t.hAlign = 'CENTER'
    story.extend([Spacer(1, 10), KeepTogether(t), Spacer(1, 10)])

def callout_row(story, cells):
    """3 callouts côte à côte (métriques)."""
    inner = []
    for big, label in cells:
        t = Table([[Paragraph('<b>%s</b>' % big, stat_s)], [Paragraph(label, statl_s)]],
                  colWidths=[150])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
            ('BOX', (0, 0), (-1, -1), 1, ACCENT),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        inner.append(t)
    wrap = Table([inner], colWidths=[AVAIL_W / 3.0] * 3, hAlign='CENTER')
    wrap.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                              ('ALIGN', (0, 0), (-1, -1), 'CENTER')]))
    story.extend([Spacer(1, 10), KeepTogether(wrap), Spacer(1, 10)])

def table(story, header, rows, ratios, caption=None, fs=9.5):
    ths = ParagraphStyle('THx', parent=th_s, fontSize=fs)
    tds = ParagraphStyle('TDx', parent=td_s, fontSize=fs)
    data = [[Paragraph('<b>%s</b>' % c, ths) for c in header]]
    for r in rows:
        data.append([c if isinstance(c, Paragraph) else Paragraph(str(c), tds) for c in r])
    widths = [r * AVAIL_W for r in ratios]
    assert sum(widths) <= AVAIL_W + 0.5, 'table overflow'
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      TABLE_ROW_ODD if i % 2 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    story.append(Spacer(1, 14))
    if caption and len(rows) <= 15:
        story.extend(safe_keep([t, Spacer(1, 5), Paragraph(caption, caption_s)]))
    else:
        story.append(t)
        if caption:
            story.extend([Spacer(1, 5), Paragraph(caption, caption_s)])
    story.append(Spacer(1, 12))

def fit_image(path, max_w, max_h):
    im = PILImage.open(path)
    ow, oh = im.size
    rw = max_w / ow if ow > max_w else 1.0
    rh = max_h / oh if oh > max_h else 1.0
    r = min(rw, rh)
    return Image(path, width=ow * r, height=oh * r)

SHOT = '/home/z/my-project/download/doc-voltrix'

def figure(story, path, caption, max_w=250, max_h=440):
    img = fit_image(path, max_w, max_h)
    img.hAlign = 'CENTER'
    story.append(Spacer(1, 12))
    story.extend(safe_keep([img, Spacer(1, 5), Paragraph(caption, caption_s)]))
    story.append(Spacer(1, 10))

story = []
